name: .NET Core

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100
    - name: Publish with dotnet
      run: dotnet publish --configuration Release
